const mongoose=require("mongoose");
require("dotenv").config();
const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true
    },
    lastName:{  
        type:String,
         required:true,
    },
    email:{
        type:String,
        required:true,
        unique:true,
    },
    password:{
        type:String,
        required:true,
    },
    accountType:{
        type:String,
        enum:["Admin","Student","Instructor"]
    },
    addDetails:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Profile"
    },
    courses:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Course"
    }],
    image:{
        type:String,    
        required:true,
    },
    token:{
        type:String,
    },//reset paswd me use ho  rha hoga
    resetPasswordExpires:{
        type:Date
    },
    courseProg:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"CourseProgress"
    }]
});
module.exports=mongoose.model("User",userSchema);